version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL} 
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME} 
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD} 
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
    driver: bridge